global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ingest'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8001']

  - job_name: 'nextjs'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
