version: '3.8'

services:
  db:
    build:
      context: ../supabase/postgres-pgvector
      dockerfile: Dockerfile
    image: polyanalysis/postgres-pgvector:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: graphrag
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  gotrue:
    image: ghcr.io/supabase/gotrue:v2.178.0
    environment:
      GOTRUE_SITE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      API_EXTERNAL_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      GOTRUE_JWT_SECRET: ${GOTRUE_JWT_SECRET}
      DATABASE_URL: ${SUPABASE_DB_URL}
      GOTRUE_DB_DRIVER: postgres
    depends_on:
      - db
    ports:
      - "9999:9999"

  postgrest:
    image: postgrest/postgrest:v13.0.5
    environment:
      PGRST_DB_URI: ${SUPABASE_DB_URL}
      PGRST_DB_SCHEMA: public,auth
      PGRST_DB_ANON_ROLE: anon
    depends_on:
      - db
    ports:
      - "3001:3000"

  realtime:
    image: ghcr.io/supabase/realtime:v2.43.1
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: graphrag
      DB_USER: postgres
      DB_PASSWORD: postgres
      RT_NO_FILE_LIMIT: 'true'
    depends_on:
      - db

  storage:
    image: ghcr.io/supabase/storage-api:v1.26.4
    environment:
      ANON_KEY: "anon"
      SERVICE_KEY: "service"
      DATABASE_URL: ${SUPABASE_DB_URL}
      PGRST_JWT_SECRET: ${GOTRUE_JWT_SECRET}
      FILE_SIZE_LIMIT: 52428800
    depends_on:
      - db

  studio:
    image: ghcr.io/supabase/studio:2025.08.25-sha-72a94af
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    ports:
      - "54330:54321"
    depends_on:
      - gotrue
      - postgrest

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage

  localai:
    image: localai/localai:latest
    ports:
      - "8081:8080"

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "3002:8080"
    environment:
      OPENAI_API_BASE_URL: http://localai:8080
    depends_on:
      - localai

  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    ports:
      - "3003:3000"
    environment:
      DATABASE_URL: ${SUPABASE_DB_URL}
      NEXTAUTH_SECRET: ${LANGFUSE_API_KEY}
    depends_on:
      - db

  flowise:
    image: flowiseai/flowise:latest
    ports:
      - "3004:3000"
    environment:
      PORT: 3000
      FLOWISE_USERNAME: ${FLOWISE_USERNAME}
      FLOWISE_PASSWORD: ${FLOWISE_PASSWORD}

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: graphrag
      DB_POSTGRESDB_HOST: db
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
    depends_on:
      - db

  rag-graph:
    image: ghcr.io/agentic-knowledge-rag/graph:latest
    ports:
      - "7000:7000"
    environment:
      DATABASE_URL: ${SUPABASE_DB_URL}
    depends_on:
      - db

volumes:
  db-data:
  qdrant-data:
